### ISSUE TITLE
More Icons

### ISSUE THREAD

**Issue by lucas-sigma** [ju1464/Electric_Funeral_Icon_Theme#2]
Hi,

I like very much your icons. So, could you add icons for JetBrains IDEs and VSCode?

**Comment by ju1464** [comment]
Done

**Comment by lucas-sigma** [comment]
Well, it's not working yet :(

**Comment by ju1464** [comment]
I do not know these applications well, I have tried installing VSCode and it does not take the icon of the theme that you are using. In my case at least I had to install it via snap, which uses the icons from another route. In this case it is /snap/vscode/72/usr/share/pixmaps/ and the icon name is code.png, I think this must be the reason. The only solution I can think of is to change the icon manually. Sorry.

**Comment by lucas-sigma** [comment]
It's ok, thanks for the support 😊
